name: deploy

on:
  push:
    tags:
      - '*'

jobs:

  # Build executable Jar files and package as a Release
  deploy-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
     
      - uses: actions/setup-java@v3
        with:
          java-version: 8.0.x
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'

      - name: Create the (jar) packages and libraries
        run: |
          ./scripts/build-ace-entities.sh --with-mysql

      - name: Get version
        id: tagName
        run: |
          VERSION=$(cat ./VERSION)
          echo "tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Zip file
        run: |
          ARCHIVE_NAME="ace-entities-${{ steps.tagName.outputs.tag }}"
          ARCHIVE_FILE="${ARCHIVE_NAME}.zip"
          zip -r ${ARCHIVE_FILE} apps/AceAS/*.jar
          zip -r ${ARCHIVE_FILE} apps/AceRS/*.jar
          zip -r ${ARCHIVE_FILE} apps/AceClient/*.jar
          zip -r ${ARCHIVE_FILE} apps/AceClientDht/*.jar
          zip -ur ${ARCHIVE_FILE} apps/lib

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tagName.outputs.tag }}
          files: |
            ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

